[general]
includes = [ 
    "**/*.rs",
    "**/*.patch",
    "**/*.json",
    "**/Dockerfile",
    "test/*.js"
]
excludes = [
    ".git/*",
    "target/*"
]

[display]
show_details = false
verbose = false
ignore_invalid_data = true