[general]
includes = [ 
    "**/*.rs",
    "**/*.patch",
    "**/*.json",
    "**/Dockerfile",
    "test/*.js"
]
excludes = [
    ".git/*",
    "target/*"
]

[display]
show_details = true
verbose = true
ignore_invalid_data = false